server:
  host: "localhost"
  port: "8000"
database:
  host: "trolley.proxy.rlwy.net"
  port: "28351"
  user: "postgres"
  password: "MPgdkeOxEXmeSRURvDPGRhAmlEgMldQn"
  dbname: "railway"
  sslmode: "disable"
secret: "KABAN"